#!/usr/bin/env python3
from os import path, mkdir

from src import setup
from src import menu


def login() -> None:
    """
    Login sequence for the user, if it is the right password they can continue, else it will quit the program

    :return: None
    """
    password = input('Password: ')
    setup.clear()

    try:  # check if folder exists
        with open("src//tmp//passhash.txt", "r") as f:
            password_hash = f.read()
    except FileNotFoundError:  # if it doens't then it creates it
        mkdir("src//tmp")
        with open("src//tmp//passhash.txt", "r") as f:
            password_hash = f.read()

    if setup.salt_hash(password) == password_hash:
        menu.encrypt_or_decrypt(password)
    else:
        quit('Bad Password!')


def login_or_generate() -> None:
    """
    Reads passhash.txt and if it has a hash in it then it assumes that the user want to login, if it doesn't exist or it
    is empty, than it creates a new profile for the user

    :return: None
    """
    if path.exists('src//tmp//passhash.txt'):
        file_read_only = open('src//tmp//passhash.txt', 'r')
        if file_read_only.read() == '':
            file_read_only.close()
            new_file = open('src//tmp//passhash.txt', 'w')
            menu.generate(new_file)
        else:
            file_read_only.close()
            login()
    else:
        try:  # check if folder exists
            write_file = open('src//tmp//passhash.txt', 'w')
            menu.generate(write_file)
        except FileNotFoundError:  # if it doesn't then it creates it
            mkdir("src//tmp")
            write_file = open('src//tmp//passhash.txt', 'w')
            menu.generate(write_file)


login_or_generate()
