#!/usr/bin/env python3
from os import path

from PassWordSafeSRC import setup
from PassWordSafeSRC import talk


def login() -> None:
    """
    Login sequence for the user, if it is the right password they can continue, else it will quit the program

    :return: None
    """
    password = input('Password: ')
    setup.clear()
    if setup.salt_hash(password):
        talk.encrypt_or_decrypt(password)
    else:
        quit('Bad Password!')


def login_or_generate() -> None:
    """
    Reads passhash.txt and if it has a hash in it then it assumes that the user want to login, if it doesn't exist or it
    is empty, than it creates a new profile for the user

    :return: None
    """
    if path.exists('PassWordSafeSRC//dat//passhash.txt'):
        file_read_only = open('PassWordSafeSRC//dat//passhash.txt', 'r')
        if file_read_only.read() == '':
            file_read_only.close()
            new_file = open('PassWordSafeSRC//dat//passhash.txt', 'w')
            talk.generate(new_file)
        else:
            file_read_only.close()
            login()
    else:
        write_file = open('PassWordSafeSRC//dat//passhash.txt', 'w')
        talk.generate(write_file)


login_or_generate()
